package ExTest_ExtensionStarterCi.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'B6EFD8B0-63F1-4FE8-AB4F-1734BD19AF8E' (id = 'ExTest_ExtensionStarterCi')
accordingly, and delete the patch script.
*/
changeProject("B6EFD8B0-63F1-4FE8-AB4F-1734BD19AF8E") {
    check(name == "extension-starter-ci") {
        "Unexpected name: '$name'"
    }
    name = "extension-starter-ci-long-running"
}
